GameSettings:
  AutoBalance: true
  MatchTimer: 200
  CountToStart: 30
  MinPlayers: 2
  MaxPlayers: 12
  MaxAngreifer: 3
  MaxVerteidiger: 2
  MusicMatch: true
  Puck:
    Material: RECORD_7
  Schlagkraft:
    Angreifer: 0.6
    Verteidiger: 0.4
    Torwart: 0.3
Messages:
  plugin-restarted: '&aHockeyGame wurde erfolgreich neu geladen.'
  gate-stored: '&aGate gespeichert.'
  hockey-stick: '&l&2Hockey Stock'
  success-sign-create: '&aSchild erfolgreich erstellt!'
  arena-success-create: '&aArena erfolgreich erstellt!'
  success-sign-remove: '&aSchild erfolgreich entfernt'
  change-class: '&aDeine Klasse wurde geandert!'
  class-full: '&cDiese Klasse ist voll. Wahle eine andere.'
  arena-full: '&cSorry. Aber die Arena ist voll. Warte ...'
  game-running: '&cSorry. Nun kommt die Match-Arena. Warte ...'
  class-does-not-exist: '&cKlasse existiert nicht'
  no-permission: '&cDafür hast du keine Rechte!'
  first-team-set-lobby: '&aKlicke auf den Block wo du die Lobby fur das erste Team haben mochtest.'
  first-team-set-spawn: '&aKlicke auf den Block wo du den Spawnpunkt fur das erste Team haben mochtest.'
  second-team-set-lobby: '&aKlicke auf den Block wo du die Lobby fur das zweite Team haben mochtest.'
  second-team-set-spawn: '&aKlicke auf den Block wo du den Spawnpunkt fur das zweite Team haben mochtest.'
  puck-set-spawn: '&aKlicke auf den Block wo du den Spawnpunkt fur den Puck haben mochtest.'
  start-create-arena: '&aWir beginnen eine Arena zu bauen. Schreibe den Namen der Arena in den Chat. Falls zu das Bau-Modus verlassen mochtest schreibe /hockey und klicke '
  second-team-empty-gates: '&cTor fur das zweite Team nicht angegeben!'
  first-team-empty-gates: '&cTor fur das erste Team nicht angegeben!'
  second-team-lobby-null: '&cLobby fur das zweite Team nicht angegeben!'
  first-team-lobby-null: '&cLobby fur das erste Team nicht angegeben!'
  second-team-spawn-null: '&cSpawnpunkt fur das zweite Team nicht angegeben!'
  first-team-spawn-null: '&cSpawnpunkt fur das erste Team nicht angegeben!'
  puck-spawn-null: '&cSpawnpunkt vom Puck nicht angegeben.'
  arena-does-not-exist: '&cArena existiert nicht'
  arena-saved: '&aArena erfolgreich gespeichert!'
  arena-name-is-taken: '&cDieser Name wird schon verwendet. Bitte wahle einen anderen.'
  select-the-first-team: '&aWahle zuerst ein Team.'
  select-the-second-team: '&aWahle ein zweites Team.'
  puck-name: '&2Puck'
  team-does-not-exist: '&cTeam existiert nicht!'
  create-arena-cancelled: '&aErstellung von einer Arena wurde abgebrochen.'
  player-not-ready: '&cDu bist nicht bereit. Wahle deine Klasse.'
  player-is-ready: '&7 ist bereit.'
  match-continues: '&aDas Spiel geht weiter! Neuer Puck im Spiel!'
  scored-goal: '&a hat einen Punkt gewonnen beim Gate '
  team-win: '&a hat das Spiel gewonnen!'
  tie: '&7Das Match endet mit Gleichstand!'
  result: '&6Endstand: '
  game-started: '&aMatch hat gestartet!'
  player-join-arena: '&6 hat die Arena betreten '
  player-leave-arena: '&6 hat die Arena verlassen '
  icon-arenas: '&6Arenen'
  icon-join-click: '&fKlicke hier um die Arena zu betreten.'
  icon-leave-click: '&fKlicke hier um die Arena zu verlassen.'
  available-arenas: '&aVerfugbare Arenen:'
  icon-reload: '&6Das Plugin wird neu geladen'
  players: '&aSpieler: '
  teams: '&aTeams: '
  available-arenas: '&aVerfugbare Arenen:'
  enabled: '&aVerfugbar: '
  icon-arena-leave: '&2Verlassen'
  start-create-team: '&aGib den Namen fur das neue Team ein (Chat). '
  select-team-color: '&aWahle eine Team-Farbe.'
  team-name-is-taken: '&cDieser Name wird schon benutzt. Bitte wahle einen anderen.'
  team-saved: '&aTeam erfolgreich gespeichert!'
  no-commands: '&aDu bist in einem Hockey-Match - benutze zuerst &e/hockey &aund klicke '
  arena-manager: Arena Manager
  team-manager: Team Manager
  icon-create-arena: '&aErstelle Arena'
  icon-delete-arena: '&cLosche Arena'
  icon-stop-arena: '&eStoppe Arena'
  icon-create-team: '&aErstelle Team'
  icon-delete-team: '&cLosche Team'
  icon-next-stage: '&3Weiter'
  set-first-gates: '&aInstalliere ein Tor fur das erste Team. Nachher schreibe /hockey und wahle &3Weiter'
  set-second-gates: '&aInstalliere ein Tor fur das zweite Team. Nachher schreibe /hockey und wahle &3Weiter'
  icon-cancel: '&cAbbrechen'
  create-team-cancelled: '&aErstellung von einem Team wurde abgebrochen.'
  arena-deleted: '&aArena erfolgreich geloscht!'
  team-deleted: '&aTeam erfolgreich geloscht!'